-- Global + room chat core schema (PostgreSQL source of truth).

do $$
begin
  if not exists (
    select 1 from pg_type where typname = 'chat_message_kind'
  ) then
    create type public.chat_message_kind as enum ('text', 'run_share', 'system');
  end if;
end $$;

create table if not exists public.global_messages (
  id bigint generated by default as identity primary key,
  user_id text references public.users(clerk_id) on delete set null,
  persona_slug text,
  kind public.chat_message_kind not null default 'text',
  content text not null check (char_length(content) between 1 and 1200),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists global_messages_created_at_idx
  on public.global_messages (created_at desc, id desc);

create table if not exists public.room_messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.study_rooms(id) on delete cascade,
  user_id text references public.users(clerk_id) on delete set null,
  kind public.chat_message_kind not null default 'text',
  content text not null check (char_length(content) between 1 and 1200),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists room_messages_room_created_idx
  on public.room_messages (room_id, created_at desc, id desc);

alter table public.global_messages enable row level security;
alter table public.room_messages enable row level security;

create policy if not exists "global_messages read all"
  on public.global_messages
  for select
  using (true);

create policy if not exists "room_messages read all"
  on public.room_messages
  for select
  using (true);

create policy if not exists "global_messages insert own"
  on public.global_messages
  for insert
  with check (auth.jwt() ->> 'sub' = user_id);

create policy if not exists "room_messages insert own"
  on public.room_messages
  for insert
  with check (auth.jwt() ->> 'sub' = user_id);

-- Demo-mode permissive anon write policies (mirrors existing demo strategy).
create policy if not exists "demo: global_messages anon all"
  on public.global_messages
  for all to anon
  using (true)
  with check (true);

create policy if not exists "demo: room_messages anon all"
  on public.room_messages
  for all to anon
  using (true)
  with check (true);

create or replace function public.insert_global_message(
  p_user_id text,
  p_content text,
  p_kind public.chat_message_kind default 'text',
  p_payload jsonb default '{}'::jsonb,
  p_persona_slug text default null
)
returns public.global_messages
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.global_messages;
begin
  insert into public.global_messages (user_id, content, kind, payload, persona_slug)
  values (p_user_id, left(trim(p_content), 1200), p_kind, coalesce(p_payload, '{}'::jsonb), p_persona_slug)
  returning * into v_row;
  return v_row;
end;
$$;

create or replace function public.insert_room_message(
  p_room_id uuid,
  p_user_id text,
  p_content text,
  p_kind public.chat_message_kind default 'text',
  p_payload jsonb default '{}'::jsonb
)
returns public.room_messages
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.room_messages;
begin
  insert into public.room_messages (room_id, user_id, content, kind, payload)
  values (p_room_id, p_user_id, left(trim(p_content), 1200), p_kind, coalesce(p_payload, '{}'::jsonb))
  returning * into v_row;
  return v_row;
end;
$$;

grant execute on function public.insert_global_message(text, text, public.chat_message_kind, jsonb, text) to anon, authenticated;
grant execute on function public.insert_room_message(uuid, text, text, public.chat_message_kind, jsonb) to anon, authenticated;

alter publication supabase_realtime add table public.global_messages;
alter publication supabase_realtime add table public.room_messages;
